Перенос статьи VEX Advanced в другой формат
pedohorse/cg-community-hub pull request #12
Opened 2024-12-15 14:02 UTC by alexwheezy

Целью было улучшить визуальную навигацию по статье, а так же упростить процедуру внесения изменений для дальшейших обновлений, если они потребуются. Cтатья перенесена в полном объёме, на 95% без искажения авторского стиля повествования.

Изменено:
 - [x] исправлены орфографические ошибки и некоторые граматические обороты чтобы немного упростить восприятие
 - [x] весь сопутствующий код теперь обёрнут в снипеты языка C, а так же изменён код-стайл (между африметическими операторами, операторами присваивания и т.д. и аргументами добавлен один пробел) чтобы улучшить читаемоесть
 - [x] добавлены метки на параграфы
 - [x] добавлены дополнительные, внешние ссылки на документацию
 - [x] важные слова, типы, символы, некоторая терминология теперь выделена в тексте
 - [ ] обновлены не все примеры hpaste в статье, у большинства истёк срок хранения
 - [x] в раздел "Функции" добавлен пример - как из тела врангла можно вернуть массив из функции
 - [x] в разделе "Структуры" обновлена информация о новом определении структур в теле врангла "на месте" начиная c H20.5

2024-12-22 17:53 UTC, pedohorse requested changes
советую визуально проверить результат, локально сбилдив сайт джекилом

2024-12-22 17:53 UTC, pedohorse commented on houdini/tutorials.md
> +* [vex advanced basics](./vex.md)
чтобы джекил правильно понял линк - это должно быть или `./vex`, или `{{ "/houdini/vex" | relative_url }}`

2024-12-22 17:53 UTC, pedohorse commented on houdini/vex.md
> +### Предисловие
перед md кодом должен быть хедер джекила для правильной концертации,
например
```
---
layout: default
---
```

2024-12-22 17:53 UTC, pedohorse commented on houdini/vex.md
> +vector y[] = {{1, 2, 3}, {2, 3.5, 4}};
джекил воспринимает `{{` как начало своих комманд, так что такие места надо эскейпить : `{\{`

2024-12-22 17:53 UTC, pedohorse commented on houdini/vex.md
> +matrix2 z[] = {{1, 2, 3, 4}, {2, 3, 4, 5}};
нужен эскейп `{\{`

2024-12-22 17:53 UTC, pedohorse commented on houdini/vex.md
> +vector arr[] = {{1, 2, 3}, {2, 3, 4}, {3, 4, 5}};
нужен эскейп `{\{`

2024-12-22 17:53 UTC, pedohorse commented on houdini/vex.md
> +printf(%f\n, arr);  // выдаст {{1, 2, 3}, {2, 3, 4}, {3, 4, 5}, {0, 0, 0}, {0, 0, 0}, {-1, -3, -5}}
нужен эскейп `{\{`

2024-12-28 16:31 UTC, alexwheezy commented
Внёс необходимые исправления, теперь текст правильно рендерится.

2024-12-29 12:28 UTC, pedohorse commented
думаю, всё хорошо.
оставшийся пункт "[ ] обновлены не все примеры hpaste в статье, у большинства истёк срок хранения" надо сделать в отдельный issue со списком сломанных линков

2024-12-29 12:28 UTC, merged